services:
  backend:
    build: ./backend
    environment:
      PG_LINK: ${PG_LINK}
    ports:
      - "8000:8000"
    networks:
      - network

  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-prod
    restart: always
    ports:
      - "8080:8080"
    networks:
      - network
    depends_on:
      - backend

networks:
  network:
    driver: bridge